checker.ts:
  file size: 2922154 # 2.92 MB
  sys allocs: 156
  sys reallocs: 5
  arena allocs: 152762
  arena reallocs: 28276
  arena size: 19271992 # 19.27 MB

App.tsx:
  file size: 415342 # 415.34 kB
  sys allocs: 63
  sys reallocs: 8
  arena allocs: 17029
  arena reallocs: 2702
  arena size: 2916664 # 2.92 MB

RadixUIAdoptionSection.jsx:
  file size: 2520 # 2.52 kB
  sys allocs: 21
  sys reallocs: 0
  arena allocs: 33
  arena reallocs: 6
  arena size: 35800 # 35.80 kB

pdf.mjs:
  file size: 567296 # 567.30 kB
  sys allocs: 2470
  sys reallocs: 205
  arena allocs: 47451
  arena reallocs: 7743
  arena size: 6359848 # 6.36 MB

antd.js:
  file size: 6686316 # 6.69 MB
  sys allocs: 1045
  sys reallocs: 56
  arena allocs: 371534
  arena reallocs: 76376
  arena size: 49051088 # 49.05 MB

binder.ts:
  file size: 193077 # 193.08 kB
  sys allocs: 34
  sys reallocs: 1
  arena allocs: 7083
  arena reallocs: 840
  arena size: 1167080 # 1.17 MB

kitchen-sink.tsx:
  file size: 732898 # 732.90 kB
  sys allocs: 1873
  sys reallocs: 175
  arena allocs: 71946
  arena reallocs: 12262
  arena size: 9546640 # 9.55 MB

